name: ROS Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, cppcheck, lint_cmake]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.1
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: foxy
        linter: ${{ matrix.linter }}
        package-name:
          diff_drive_controller
          effort_controllers
          forward_command_controller
          joint_state_broadcaster
          joint_state_controller
          joint_trajectory_controller
          position_controllers
          ros2_controllers
          velocity_controllers

  ament_lint_cpplint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cpplint]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.1
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: foxy
        linter: cpplint
        arguments: "--filter=-whitespace/newline"
        package-name:
          diff_drive_controller
          effort_controllers
          forward_command_controller
          joint_state_broadcaster
          joint_state_controller
          joint_trajectory_controller
          position_controllers
          ros2_controllers
          velocity_controllers
